import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.io.FileWriter;
import java.io.IOException;

public class LihatLaporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuDashboard.class.getName());

    /**
     * Creates new form MenuDashboard
     */
    public LihatLaporan() {
        initComponents();
        setTitle("Lihat Laporan");
        setLocationRelativeTo(null);
        formListenerSetup();
        loadData();
        hitungTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahLaporan1 = new TambahLaporan();
        jPanel3 = new javax.swing.JPanel();
        lblTambahLaporan = new javax.swing.JLabel();
        lblLihatLaporan = new javax.swing.JLabel();
        lblProfil = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPemasukan = new javax.swing.JLabel();
        lblPengeluaran = new javax.swing.JLabel();
        lblSisa = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 100));

        lblTambahLaporan.setForeground(new java.awt.Color(255, 255, 255));
        lblTambahLaporan.setText("Tambah Laporan");
        lblTambahLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTambahLaporanMouseClicked(evt);
            }
        });

        lblLihatLaporan.setText("Lihat Laporan");
        lblLihatLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLihatLaporanMouseClicked(evt);
            }
        });

        lblProfil.setForeground(new java.awt.Color(255, 255, 255));
        lblProfil.setText("Profil");
        lblProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfilMouseClicked(evt);
            }
        });

        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 0, 0));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboard)
                .addGap(77, 77, 77))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(lblTambahLaporan))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(lblProfil))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(lblLihatLaporan))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lblDashboard)
                .addGap(36, 36, 36)
                .addComponent(lblTambahLaporan)
                .addGap(32, 32, 32)
                .addComponent(lblLihatLaporan)
                .addGap(38, 38, 38)
                .addComponent(lblProfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(9, 65, 125));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        TabelLaporan.setBackground(new java.awt.Color(242, 242, 242));
        TabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Kategori", "Jenis", "Nominal", "Catatan", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(TabelLaporan);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Total Pemasukan:");

        jLabel2.setText("Total Pengeluaran:");

        jLabel3.setText("Sisa Uang:");

        lblPemasukan.setText("-");

        lblPengeluaran.setText("-");

        lblSisa.setText("-");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addGap(29, 29, 29)
                        .addComponent(btnSimpan)
                        .addGap(27, 27, 27)
                        .addComponent(btnEdit)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPemasukan))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPengeluaran))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSisa)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void loadData() {
    // 1️⃣ Ambil model dari JTable
    DefaultTableModel model = (DefaultTableModel) TabelLaporan.getModel();
    model.setRowCount(0); // bersihkan tabel sebelum isi ulang

    double totalPemasukan = 0;
    double totalPengeluaran = 0;

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/smartkas", "root", "");
         PreparedStatement ps = conn.prepareStatement("SELECT * FROM laporan");
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id"),
                rs.getString("kategori"),
                rs.getString("jenis"),
                rs.getDouble("nominal"),
                rs.getString("catatan"),
                rs.getString("tanggal")
            };
            model.addRow(row);

            if (rs.getString("jenis").equalsIgnoreCase("Pemasukan")) {
                totalPemasukan += rs.getDouble("nominal");
            } else {
                totalPengeluaran += rs.getDouble("nominal");
            }
        }

        // Update label total
        lblPemasukan.setText(String.valueOf(totalPemasukan));
        lblPengeluaran.setText(String.valueOf(totalPengeluaran));
        lblSisa.setText(String.valueOf(totalPemasukan - totalPengeluaran));

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error saat memuat data: " + e.getMessage());
    }
}


// ====== HITUNG TOTAL PEMASUKAN, PENGELUARAN, SISA ======
private void hitungTotal() {
    DefaultTableModel model = (DefaultTableModel) TabelLaporan.getModel();

    double totalPemasukan = 0;
    double totalPengeluaran = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        String jenis = model.getValueAt(i, 2).toString(); // kolom ke-2 = 'jenis'
        double nominal = Double.parseDouble(model.getValueAt(i, 3).toString()); // kolom ke-3 = 'nominal'

        if (jenis.equalsIgnoreCase("Pemasukan")) {
            totalPemasukan += nominal;
        } else if (jenis.equalsIgnoreCase("Pengeluaran")) {
            totalPengeluaran += nominal;
        }
    }

    lblPemasukan.setText(String.valueOf(totalPemasukan));
    lblPengeluaran.setText(String.valueOf(totalPengeluaran));
    lblSisa.setText(String.valueOf(totalPemasukan - totalPengeluaran));
}


    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin logout?", 
        "Konfirmasi Logout", 
        javax.swing.JOptionPane.YES_NO_OPTION);
    
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblTambahLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTambahLaporanMouseClicked

    private void lblLihatLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLihatLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLihatLaporanMouseClicked

    private void lblProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProfilMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Simpan Laporan Sebagai");

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File selectedFile = fileChooser.getSelectedFile();

        try {
            SimpanService.exportCSV(
                TabelLaporan,
                lblPemasukan.getText(),
                lblPengeluaran.getText(),
                lblSisa.getText(),
                selectedFile
            );

            javax.swing.JOptionPane.showMessageDialog(this,
                "Laporan berhasil disimpan!");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal menyimpan file: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TabelLaporan.getModel();
        int selectedRow = TabelLaporan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
            return;
        }

        int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/smartkas", "root", "");
                PreparedStatement ps = conn.prepareStatement("DELETE FROM laporan WHERE id = ?")) {

                ps.setInt(1, id);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                model.removeRow(selectedRow);
                hitungTotal();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TabelLaporan.getModel();
        int selectedRow = TabelLaporan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!");
            return;
        }

        int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        String kategoriBaru = JOptionPane.showInputDialog(this, "Masukkan kategori baru:", model.getValueAt(selectedRow, 1));
        String jenisBaru = JOptionPane.showInputDialog(this, "Masukkan jenis (Pemasukan/Pengeluaran):", model.getValueAt(selectedRow, 2));
        String nominalStr = JOptionPane.showInputDialog(this, "Masukkan nominal baru:", model.getValueAt(selectedRow, 3));
        String catatanBaru = JOptionPane.showInputDialog(this, "Masukkan catatan baru:", model.getValueAt(selectedRow, 4));
        String tanggalBaru = JOptionPane.showInputDialog(this, "Masukkan tanggal baru (YYYY-MM-DD):", model.getValueAt(selectedRow, 5));

        if (kategoriBaru == null || jenisBaru == null || nominalStr == null || tanggalBaru == null) {
            JOptionPane.showMessageDialog(this, "Edit dibatalkan.");
            return;
        }

        double nominalBaru = Double.parseDouble(nominalStr);

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/smartkas", "root", "");
            PreparedStatement ps = conn.prepareStatement(
                "UPDATE laporan SET kategori=?, jenis=?, nominal=?, catatan=?, tanggal=? WHERE id=?")) {

            ps.setString(1, kategoriBaru);
            ps.setString(2, jenisBaru);
            ps.setDouble(3, nominalBaru);
            ps.setString(4, catatanBaru);
            ps.setString(5, tanggalBaru);
            ps.setInt(6, id);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

            // update di tabel
            model.setValueAt(kategoriBaru, selectedRow, 1);
            model.setValueAt(jenisBaru, selectedRow, 2);
            model.setValueAt(nominalBaru, selectedRow, 3);
            model.setValueAt(catatanBaru, selectedRow, 4);
            model.setValueAt(tanggalBaru, selectedRow, 5);

            hitungTotal();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed


    private void formListenerSetup() {
    // Klik Dashboard
    lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new MenuDashboard().setVisible(true);
            dispose();
        }
    });
    
    // Klik Tambah Laporan
    lblTambahLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new TambahLaporan().setVisible(true);
            dispose();
        }
    });
    
    // Klik Lihat Laporan
    lblLihatLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new LihatLaporan().setVisible(true);
            dispose();
        }
    });
    
    // Klik Profil
    lblProfil.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new Profil().setVisible(true);
            dispose();
        }
    });
    
    lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTambahLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblLihatLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblProfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelLaporan;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblLihatLaporan;
    private javax.swing.JLabel lblPemasukan;
    private javax.swing.JLabel lblPengeluaran;
    private javax.swing.JLabel lblProfil;
    private javax.swing.JLabel lblSisa;
    private javax.swing.JLabel lblTambahLaporan;
    private TambahLaporan tambahLaporan1;
    // End of variables declaration//GEN-END:variables
}
