import java.sql.*;
import java.sql.Connection;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class TambahLaporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuDashboard.class.getName());

    /**
     * Creates new form MenuDashboard
     */
    public TambahLaporan() {
        initComponents();
        setTitle("TambahLaporan");
        setLocationRelativeTo(null);
        formListenerSetup();
        jComboBox1.addActionListener(e -> updateKategori());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTambahLaporan = new javax.swing.JLabel();
        lblLihatLaporan = new javax.swing.JLabel();
        lblProfil = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jtxtNominal = new javax.swing.JTextField();
        jtxtCatatan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 100));

        lblTambahLaporan.setText("Tambah Laporan");
        lblTambahLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTambahLaporanMouseClicked(evt);
            }
        });

        lblLihatLaporan.setForeground(new java.awt.Color(255, 255, 255));
        lblLihatLaporan.setText("Lihat Laporan");
        lblLihatLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLihatLaporanMouseClicked(evt);
            }
        });

        lblProfil.setForeground(new java.awt.Color(255, 255, 255));
        lblProfil.setText("Profil");
        lblProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfilMouseClicked(evt);
            }
        });

        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 0, 0));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboard)
                .addGap(77, 77, 77))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblTambahLaporan))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblProfil))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogOut)
                            .addComponent(lblLihatLaporan))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lblDashboard)
                .addGap(36, 36, 36)
                .addComponent(lblTambahLaporan)
                .addGap(32, 32, 32)
                .addComponent(lblLihatLaporan)
                .addGap(38, 38, 38)
                .addComponent(lblProfil)
                .addGap(90, 90, 90)
                .addComponent(btnLogOut)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(9, 65, 125));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Jenis");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Kategori");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Nominal");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Catatan");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tanggal");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaji", "Hadiah", "Investasi", "Penjualan", "Lainnya" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jtxtNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNominalActionPerformed(evt);
            }
        });

        jtxtCatatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCatatanActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 204, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtCatatan)
                            .addComponent(jtxtNominal)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(62, 62, 62)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method untuk menyesuaikan kategori berdasarkan jenis
private void updateKategori() {
    String jenis = jComboBox1.getSelectedItem().toString();
    jComboBox2.removeAllItems(); // hapus semua kategori lama

    if (jenis.equals("Pemasukan")) {
        jComboBox2.addItem("Gaji");
        jComboBox2.addItem("Hadiah");
        jComboBox2.addItem("Investasi");
        jComboBox2.addItem("Penjualan");
        jComboBox2.addItem("Lainnya");
    } else if (jenis.equals("Pengeluaran")) {
        jComboBox2.addItem("Makanan");
        jComboBox2.addItem("Transportasi");
        jComboBox2.addItem("Pendidikan");
        jComboBox2.addItem("Kesehatan");
        jComboBox2.addItem("Hiburan");
        jComboBox2.addItem("Tagihan");
        jComboBox2.addItem("Lainnya");
    }
}


    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblTambahLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTambahLaporanMouseClicked

    private void lblLihatLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLihatLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLihatLaporanMouseClicked

    private void lblProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProfilMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin logout?", 
        "Konfirmasi Logout", 
        javax.swing.JOptionPane.YES_NO_OPTION);
    
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jtxtNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNominalActionPerformed

    private void jtxtCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCatatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCatatanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
     String jenis = jComboBox1.getSelectedItem().toString();
    String kategori = jComboBox2.getSelectedItem().toString();
    String nominalText = jtxtNominal.getText().trim();
    String catatan = jtxtCatatan.getText().trim();

    // Ambil tanggal dari JDateChooser
    java.util.Date selectedDate = jDateChooser1.getDate();

    // Validasi input
    if (nominalText.isEmpty() || selectedDate == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nominal dan Tanggal wajib diisi!");
        return;
    }

    double nominal;
    try {
        nominal = Double.parseDouble(nominalText);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nominal harus berupa angka!");
        return;
    }

    // Format tanggal ke MySQL (YYYY-MM-DD)
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(selectedDate);

    try (java.sql.Connection conn = Koneksi.getKoneksi()) {

        // --- Cek apakah kategori sudah ada di tabel categories ---
        int categoryId = 0;
        String sqlKategori = "SELECT id FROM categories WHERE name = ?";
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sqlKategori)) {
            ps.setString(1, kategori);
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    categoryId = rs.getInt("id");
                } else {
                    // Jika belum ada, tambahkan otomatis
                    String insertKategori = "INSERT INTO categories (name, user_id) VALUES (?, ?)";
                    try (java.sql.PreparedStatement ps2 = conn.prepareStatement(insertKategori, java.sql.Statement.RETURN_GENERATED_KEYS)) {
                        ps2.setString(1, kategori);
                        ps2.setInt(2, 1); // user_id default 1
                        ps2.executeUpdate();
                        try (java.sql.ResultSet rs2 = ps2.getGeneratedKeys()) {
                            if (rs2.next()) categoryId = rs2.getInt(1);
                        }
                    }
                }
            }
        }

        // --- Simpan data ke tabel laporan ---
        String sqlInsert = "INSERT INTO laporan (kategori, jenis, nominal, catatan, tanggal) VALUES (?, ?, ?, ?, ?)";
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sqlInsert)) {
            ps.setString(1, kategori); // simpan nama kategori, bukan id
            ps.setString(2, jenis);
            ps.setDouble(3, nominal);
            ps.setString(4, catatan);
            ps.setString(5, tanggal);
            ps.executeUpdate();
        }

        javax.swing.JOptionPane.showMessageDialog(this, "✅ Data berhasil disimpan!");

        // Kosongkan form setelah disimpan
        jtxtNominal.setText("");
        jtxtCatatan.setText("");
        jDateChooser1.setDate(null);

        // Tampilkan ulang form laporan
        new LihatLaporan().setVisible(true);
        dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "❌ Gagal menyimpan data: " + e.getMessage());
    }


    }//GEN-LAST:event_btnSimpanActionPerformed
private void formListenerSetup() {
    // Klik Dashboard
    lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new MenuDashboard().setVisible(true);
            dispose();
        }
    });
    
    // Klik Tambah Laporan
    lblTambahLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new TambahLaporan().setVisible(true);
            dispose();
        }
    });
    
    // Klik Lihat Laporan
    lblLihatLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new LihatLaporan().setVisible(true);
            dispose();
        }
    });
    
    // Klik Profil
    lblProfil.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new Profil().setVisible(true);
            dispose();
        }
    });
    
    lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTambahLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblLihatLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblProfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtxtCatatan;
    private javax.swing.JTextField jtxtNominal;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblLihatLaporan;
    private javax.swing.JLabel lblProfil;
    private javax.swing.JLabel lblTambahLaporan;
    // End of variables declaration//GEN-END:variables
}
